# Generated by Django 4.1.1 on 2022-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_personal_info_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='profile_Picture',
            field=models.URLField(blank=True, max_length=70000, null=True),
        ),
    ]
