# Generated by Django 4.1.1 on 2022-10-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_personal_info_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='profile_Picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
