# Generated by Django 4.0 on 2022-10-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('seller', '0005_alter_personal_info_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to='auth.user'),
        ),
    ]
