# Generated by Django 4.0 on 2022-11-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_personal_info_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
