# Generated by Django 4.0 on 2022-11-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_personal_info_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_info',
            old_name='profile_Picture',
            new_name='avatar',
        ),
    ]
