# Generated by Django 4.0 on 2022-11-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_rename_profile_picture_personal_info_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.skill_levels'),
        ),
    ]
