# Generated by Django 4.0 on 2022-12-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_skill_levels_alter_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='location',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
