# Generated by Django 4.0 on 2023-02-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_personal_info_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='slogan',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
