# Generated by Django 4.0 on 2023-07-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_personal_info_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='impression',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
