# Generated by Django 4.1.1 on 2022-10-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_category_image_overview_file_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.FileField(blank=True, null=True, upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='search_keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='service_type',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service_type',
            name='sub_category',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='body',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='file_update',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='is_project',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='is_request',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='search_keyword',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='can_publish',
        ),
        migrations.AddField(
            model_name='overview',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='meta_video/'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='delivery_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='heading',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='packages',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publish',
            name='suspend_message',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='meta_images/'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='Service_Type',
        ),
        migrations.AddField(
            model_name='service_offer',
            name='Price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.pricing'),
        ),
        migrations.AddField(
            model_name='service_offer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.overview'),
        ),
        migrations.AddField(
            model_name='search_keyword',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.overview'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.overview'),
        ),
    ]
