# Generated by Django 4.1.1 on 2022-10-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_pdf_search_keyword_service_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Description_FAQ',
        ),
    ]
