# Generated by Django 4.1.1 on 2022-10-16 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0006_alter_publish_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 16, 14, 28, 5, 951141, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
