# Generated by Django 4.0 on 2022-11-01 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0009_alter_publish_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_pricing', to='meta.overview'),
        ),
    ]
