# Generated by Django 4.0 on 2022-11-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0010_alter_pricing_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search_keyword',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword', to='meta.overview'),
        ),
    ]
