# Generated by Django 4.0 on 2022-12-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0011_overview_progress_alter_search_keyword_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
