# Generated by Django 4.0 on 2023-02-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0012_overview_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overview',
            old_name='Meta_Title',
            new_name='title',
        ),
    ]
