# Generated by Django 4.0 on 2023-08-06 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0013_rename_meta_title_overview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='meta.overview'),
        ),
    ]
