# Generated by Django 4.0 on 2023-02-02 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatMessage_to', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatMessage_from', to='auth.user'),
        ),
    ]
