# Generated by Django 4.0 on 2023-02-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0011_personal_info_slogan'),
        ('projectApp', '0004_project_overview_created'),
        ('meta', '0012_overview_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_address', models.CharField(max_length=50)),
                ('payment_hash', models.CharField(max_length=50)),
                ('smart_contract', models.CharField(max_length=50)),
                ('payed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('browser', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('cp', 'Completed'), ('pd', 'Pending'), ('dc', 'Decline'), ('cd', 'Cancelled')], default='pd', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='seller.personal_info')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='seller.personal_info')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_order', to='projectApp.project_overview')),
            ],
        ),
        migrations.CreateModel(
            name='Meta_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('cp', 'Completed'), ('pd', 'Pending'), ('dc', 'Decline'), ('cd', 'Cancelled')], default='pd', max_length=3)),
                ('completed', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.payment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_order', to='meta.overview')),
            ],
        ),
    ]
