# Generated by Django 4.0 on 2023-02-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_order',
            name='download',
            field=models.BooleanField(default=False),
        ),
    ]
