# Generated by Django 4.0 on 2023-02-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project_order_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_order',
            name='download',
        ),
    ]
