# Generated by Django 4.0 on 2023-02-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_project_order_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta_order',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
