# Generated by Django 4.0 on 2023-02-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_meta_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
