# Generated by Django 4.0 on 2023-02-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_meta_order_service_alter_project_order_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta_order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Decline', 'Decline'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='project_order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Decline', 'Decline'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
