# Generated by Django 4.0 on 2023-02-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_personal_info_slogan'),
        ('dashboard', '0007_alter_meta_order_status_alter_project_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta_order',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='seller.personal_info'),
        ),
        migrations.AddField(
            model_name='meta_order',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='seller.personal_info'),
        ),
        migrations.DeleteModel(
            name='Project_Order',
        ),
    ]
