# Generated by Django 4.0 on 2023-02-21 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0008_meta_order_buyer_meta_order_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta_order',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='auth.user'),
        ),
    ]
