# Generated by Django 4.0 on 2023-02-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_meta_order_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta_order',
            name='price',
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
