# Generated by Django 4.0 on 2022-12-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_project_overview_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_overview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
