# Generated by Django 4.0 on 2023-02-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_project_overview_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_overview',
            old_name='project_Title',
            new_name='title',
        ),
    ]
